server:
  port: 8001
spring:
  application:
    name: microservice-provider-user    # 项目名称尽量用小写

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true